#!/bin/bash

# Function to handle user exit
function handle_exit {
    echo "Exiting..."
    exit 0
}

# Set the path to aliasfile relative to package root
aliasfile_path="./usr/local/configs/aliasfile"
percep_path="./usr/local/configs/perception.rviz"
binaries_path="./usr/local/scripts/"
search_string="export ZT_IP=<zerotier.ip>"

# Get the user's home directory
user_home_dir="$HOME"


# Define the path to the ~/.bash_aliases file
aliases_file="$HOME/.bash_aliases"

getzt(){
    while true; do
            read -p "Enter your ZeroTier IP or type 'exit' to quit: " zerotier_ip
            if [ "$zerotier_ip" = "exit" ]; then
                handle_exit
            fi
            if [[ ! $zerotier_ip =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
                echo "Invalid IP format. Please install ZeroTier, get your IP, and enter it."
            else
                break  # Exit the loop if a valid IP is entered
            fi
}

# Check if the file exists
if [ -e "$aliases_file" ]; then
    # Use grep to search for an IP address pattern in the file
    if grep -qE '\b([0-9]{1,3}\.){3}[0-9]{1,3}\b' "$aliases_file"; then
        # IP address found, so output it
        echo "IP found in $aliases_file:"
        grep -oE '\b([0-9]{1,3}\.){3}[0-9]{1,3}\b' "$aliases_file"
        zerotier_ip="$ZT_IP"
    else
        # No IP address found
        echo "No IP found in $aliases_file"
        getzt
    done   


    fi
else
    # File does not exist
    echo "File $aliases_file does not exist."
fi

logged_in_user="$SUDO_USER"

alias_content=$(cat "$aliasfile_path")

# Replace ZeroTier IP placeholder in the alias content
alias_content=$(echo "$alias_content" | sed "s/<zerotier.ip>/$zerotier_ip/g")

user_home="/home/$logged_in_user"
bash_aliases="$user_home/.bash_aliases"

if [ -f "$bash_aliases" ]; then
    mv "$bash_aliases" "$bash_aliases.backup"
fi

echo "$alias_content" > "$bash_aliases"

if [ $? -eq 0 ]; then
    echo "Alias file updated with ZeroTier IP."
else
    echo "Error updating alias file."
fi

# Specify the full path for copying binaries within package root
for executable in "$binaries_path"*; do
    if [ -f "$executable" ]; then
        sudo cp "$executable" "$DESTDIR/usr/bin/"
        sudo chmod +x "$DESTDIR/usr/bin/$(basename "$executable")"
    fi
done

# back up peception file
cp /opt/ros/noetic/share/rviz/default.rviz /opt/ros/noetic/share/rviz/default_bak.rviz
# copy perception file into correct location 
cp "$percep_path" /opt/ros/noetic/share/rviz/default.rviz

echo "Additional executables installed."

# Source .bash_aliases
if [ -f "$bash_aliases" ]; then
    source "$bash_aliases"
    echo "bash_aliases sourced."
else
    echo "bash_aliases not found."
fi

# Welcome message with usage instructions
echo "Installation completed!"
echo "Welcome to robo hustler!"
echo "Next time you open a terminal just type howdoi followed by a keyword"
echo "Alternatively type how to for a full usage list"
echo "Now type exit and press enter"